/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbwarung;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Hadits
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_user = new javax.swing.JTextField();
        id_ped = new javax.swing.JLabel();
        pw = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        pw_user = new javax.swing.JPasswordField();
        btn_login1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setText("Login Warung Gaul");

        id_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_userActionPerformed(evt);
            }
        });

        id_ped.setText("ID");

        pw.setText("Password");

        btn_login.setText("LOGIN");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_login1.setText("Register");
        btn_login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_login1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_ped)
                            .addComponent(pw))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_user, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pw_user, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_login)
                                .addGap(94, 94, 94)
                                .addComponent(btn_login1)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_user, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_ped))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pw)
                    .addComponent(pw_user, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login1)
                    .addComponent(btn_login))
                .addGap(62, 62, 62))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_userActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
//        try{
//            if(id_user.getText().equals("")){
//                JOptionPane.showMessageDialog(this, "Silahkan Isi Username anda", "Caution", JOptionPane.WARNING_MESSAGE);
//                pw_user.setText("");
//                id_user.requestFocus();
//            }
//            else if(pw_user.getText().equals("")){
//                JOptionPane.showMessageDialog(this, "Silahkan Isi Password anda", "Caution", JOptionPane.WARNING_MESSAGE);
//                pw_user.requestFocus();
//            }
//            else{
//                Dbwarung konek = new Dbwarung();
//                Connection kon = konek.bukaKoneksi();
//                Statement stat = kon.createStatement();
//                //Menyocokkan akun yang berada di database
//                String Query = "SELECT * FROM users WHERE Username = '"+id_user.getText()+"' AND Password = '"+pw_user.getText()+"'";
//                ResultSet rs = stat.executeQuery(Query);
//                JOptionPane.showMessageDialog(this, "Login Success");
//                Home hm = new Home();
//                hm.setVisible(true);
//                this.dispose();
//                }
//                kon.close();
//            
//        }
//        catch(Exception e){
//            JOptionPane.showMessageDialog(this, e);
//        }
PreparedStatement psGudang, psKasir, psPelanggan;
        ResultSet rsGudang,rsKasir, rsPelanggan;
        String username = id_user.getText();
        String password = String.valueOf(pw_user.getPassword());
        
        if(username.equals("") && password.equals("")){
            JOptionPane.showMessageDialog(null,"Silahkan isi field untuk login");
        }else{
        
        String query = "SELECT * FROM `user` WHERE `ID` = ? AND `PASSWORD` = ? AND status = 1";
        String query2= "SELECT * FROM `user` WHERE `ID` = ? AND `PASSWORD` = ? AND status = 2";
        String query3= "SELECT * FROM `user` WHERE `ID` = ? AND `PASSWORD` = ? AND status = 3";
        try {
            psGudang = Dbwarung.bukaKoneksi().prepareStatement(query);      
            psGudang.setString(1, username);
            psGudang.setString(2, password);
            rsGudang = psGudang.executeQuery();
            
            psKasir = Dbwarung.bukaKoneksi().prepareStatement(query2);
            psKasir.setString(1, username);
            psKasir.setString(2, password);
            rsKasir = psKasir.executeQuery();
            
            psPelanggan = Dbwarung.bukaKoneksi().prepareStatement(query3);
            psPelanggan.setString(1, username);
            psPelanggan.setString(2, password);
            rsPelanggan = psPelanggan.executeQuery();
            
            if(rsGudang.next()){
                JOptionPane.showMessageDialog(null,"Login Sebagai Petugas Warung");
                    Home Home = new Home();
                    Home.setVisible(true);
                    Home.pack();
                    Home.setLocationRelativeTo(null);
                    Home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
            }else if(rsKasir.next()){
                JOptionPane.showMessageDialog(null,"Login Sebagai Kasir");
                    V_bayar V_bayar = new V_bayar();
                    V_bayar.setVisible(true);
                    V_bayar.pack();
                    V_bayar.setLocationRelativeTo(null);
                    V_bayar.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();              
            }else if(rsPelanggan.next()){
                JOptionPane.showMessageDialog(null,"Haloo!, Selamat Datang di Warung Gaul");
                    Order or = new Order();
                    or.setVisible(true);
                    or.pack();
                    or.setLocationRelativeTo(null);
                    or.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    this.dispose();
            }else{
                JOptionPane.showMessageDialog(null,"Username atau Password salah");
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_login1ActionPerformed
        // TODO add your handling code here:
        FormRegis fr = new FormRegis();
        fr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_login1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_login1;
    private javax.swing.JLabel id_ped;
    private javax.swing.JTextField id_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel pw;
    private javax.swing.JPasswordField pw_user;
    // End of variables declaration//GEN-END:variables
}
