/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbwarung;

import java.sql.Connection;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hadits
 */
public class Produkjadi extends javax.swing.JFrame {

    /**
     * Creates new form Produkjadi
     */
    public Produkjadi() {
        initComponents();
        load_table();
        kosong();
        load_pemasok_masuk();
        gatherTanggal();
        gatherBulan();
        gatherTahun();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        stock_produk = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        txtNamaB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        harga_satuan = new javax.swing.JTextField();
        txtstock = new javax.swing.JLabel();
        id_produk = new javax.swing.JTextField();
        txtstock2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nama_produk = new javax.swing.JTextField();
        btnlogout = new javax.swing.JButton();
        txtstock1 = new javax.swing.JLabel();
        cmbSupp = new javax.swing.JComboBox();
        txtstock3 = new javax.swing.JLabel();
        tanggal = new javax.swing.JComboBox();
        bulan = new javax.swing.JComboBox();
        tahun = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        stock_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stock_produkActionPerformed(evt);
            }
        });

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        txtNamaB.setText("Nama Produk");

        jLabel1.setText("Id Produk");

        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID_PRODUK", "ID_PEMASOK", "NAMA_PRODUK", "STOCK", "HARGA_SATUAN"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        harga_satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harga_satuanActionPerformed(evt);
            }
        });

        txtstock.setText("Stock");

        id_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_produkActionPerformed(evt);
            }
        });

        txtstock2.setText("Harga Satuan");

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel4.setText("Kelola Produk Jadi");

        nama_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_produkActionPerformed(evt);
            }
        });

        btnlogout.setText("Logout");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        txtstock1.setText("Id Pemasok");

        cmbSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSuppActionPerformed(evt);
            }
        });

        txtstock3.setText("Tanggal Beli");

        tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtstock2)
                    .addComponent(txtstock)
                    .addComponent(txtNamaB)
                    .addComponent(txtstock1)
                    .addComponent(jLabel1)
                    .addComponent(txtstock3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(id_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stock_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(345, 345, 345)
                        .addComponent(jLabel4))
                    .addComponent(cmbSupp, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(harga_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtstock1)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txtNamaB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtstock)))
                        .addGap(18, 18, 18)
                        .addComponent(txtstock2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbSupp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stock_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(harga_satuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstock3)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(btnlogout)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kosong(){
        
        id_produk.setText(null);
        
        nama_produk.setText(null);
        stock_produk.setText(null);
        harga_satuan.setText(null);
    }
    
    private void load_table(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("NO");
        model.addColumn("id produk");
        model.addColumn("id pemasok");
        model.addColumn("nama produk");
        model.addColumn("stock produk");
        model.addColumn("harga satuan");
        
        try{
            int no = 1;
            Dbwarung konek = new Dbwarung();
                Connection kon = konek.bukaKoneksi();
                Statement stat = kon.createStatement();
            String sql = "SELECT * FROM produk_jadi INNER JOIN pemasok ON produk_jadi.ID_PEMASOK = pemasok.ID_PEMASOK";
            java.sql.ResultSet res=stat.executeQuery(sql);
            while(res.next()){
                DateFormat dfto = new SimpleDateFormat("dd MMMM yyyy");
                DateFormat dffrom = new SimpleDateFormat("yyyy-MM-dd");  
                Date today = dffrom.parse(res.getString(6));
                String s = dfto.format(today);
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),s});
            }
            jTable1.setModel(model);
        }catch(Exception e){
            
        }
    }
    public void load_pemasok_masuk() {
        try{
            int no = 1;
            Dbwarung konek = new Dbwarung();
                Connection kon = konek.bukaKoneksi();
                Statement stat = kon.createStatement();
            String sql = "SELECT * FROM pemasok";
            java.sql.ResultSet res=stat.executeQuery(sql);
            while(res.next()){
                cmbSupp.addItem(res.getString(1));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e, "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            Dbwarung konek = new Dbwarung();
            Connection kon = konek.bukaKoneksi();
            Statement stat = kon.createStatement();
            String sql = "DELETE FROM produk_jadi WHERE ID_PRODUK = '"+id_produk.getText()+"' ";
            int rows = stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(this,"Data Berhasil Di hapus","Information", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void stock_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stock_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stock_produkActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
            String query = "UPDATE produk_jadi set ID_PRODUK ='"+id_produk.getText()+"',ID_PEMASOK='"+cmbSupp.getSelectedItem().toString()+"',NAMA_PRODUK='"+nama_produk.getText().toString()+"',STOK='"+stock_produk.getText().toString()+"',HARGA_SATUAN='"+harga_satuan.getText().toString()+"' where ID_PRODUK = '"+id_produk.getText()+"'";
            java.sql.Connection kon=(Connection)Dbwarung.bukaKoneksi();
            java.sql.PreparedStatement ps=kon.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Databerhasil di edit");

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "perubahan data gagal"+e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String code = jTable1.getValueAt(baris, 1).toString();
        id_produk.setText(code);
        String supp = jTable1.getValueAt(baris, 2).toString();
        cmbSupp.setSelectedItem(supp);
        String nm = jTable1.getValueAt(baris, 3).toString();
        nama_produk.setText(nm);
        String stk = jTable1.getValueAt(baris, 4).toString();
        stock_produk.setText(stk);
        String hg = jTable1.getValueAt(baris, 5).toString();
        harga_satuan.setText(hg);

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Produkjadi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void harga_satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harga_satuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_harga_satuanActionPerformed

    private void id_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_produkActionPerformed

    public void gatherTanggal() {
        for(int i = 1; i <= 31; i++){
            tanggal.addItem(i);
        }
    }
    public void gatherBulan() {
        for(int i = 1; i <= 12; i++){
            bulan.addItem(i);
        }
    }
    public void gatherTahun() {
        for(int i = 2020; i >= 1990; i--){
            tahun.addItem(i);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            if(id_produk.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Kode Barang can't be empty", "WARNING", JOptionPane.WARNING_MESSAGE);

                nama_produk.setText("");

                harga_satuan.setText("");
                stock_produk.setText("");
                id_produk.requestFocus();
            }else if(cmbSupp.getSelectedItem().equals("")){
                JOptionPane.showMessageDialog(this, "Stock can't be empty", "WARNING", JOptionPane.WARNING_MESSAGE);
               
                id_produk.setText("");
                nama_produk.setText("");
                harga_satuan.setText("");
                stock_produk.setText("");
                
            }
            else if(nama_produk.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Nama Barang can't be empty", "WARNING", JOptionPane.WARNING_MESSAGE);

                id_produk.setText("");

                harga_satuan.setText("");
                stock_produk.setText("");
                nama_produk.requestFocus();

            }else if(harga_satuan.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Harga can't be empty", "WARNING", JOptionPane.WARNING_MESSAGE);

                id_produk.setText("");
                nama_produk.setText("");
                stock_produk.setText("");
                harga_satuan.requestFocus();
            }else if(stock_produk.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Harga can't be empty", "WARNING", JOptionPane.WARNING_MESSAGE);

                id_produk.setText("");
                nama_produk.setText("");
                harga_satuan.setText("");
                stock_produk.requestFocus();
            }
            else{
                Dbwarung konek = new Dbwarung();
                Connection kon = konek.bukaKoneksi();
                Statement stat = kon.createStatement();
                String sql = "SELECT * from pemasok,produk_jadi where produk_jadi.ID_PEMASOK = '"+cmbSupp.getSelectedItem()+"' AND pemasok.ID_PEMASOK = produk_jadi.ID_PEMASOK";
                java.sql.ResultSet res = stat.executeQuery(sql);
                res.next();
                String datez = tahun.getSelectedItem().toString() +"-"+ bulan.getSelectedItem().toString() +"-"+ tanggal.getSelectedItem().toString();
                String query = "INSERT INTO `produk_jadi`(`ID_PRODUK`, `ID_PEMASOK`, `NAMA_PRODUK`,`STOK`,`HARGA_SATUAN`,`TANGGAL`) VALUES ('"+id_produk.getText()+"','"+cmbSupp.getSelectedItem().toString()+"','"+nama_produk.getText()+"','"+stock_produk.getText()+"','"+harga_satuan.getText()+"','"+datez+"')";
                int rows = stat.executeUpdate(query);
                JOptionPane.showMessageDialog(this, "Data Berhasil di Input", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nama_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nama_produkActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void cmbSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSuppActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSuppActionPerformed

    private void tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produkjadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produkjadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produkjadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produkjadi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produkjadi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogout;
    private javax.swing.JComboBox bulan;
    private javax.swing.JComboBox cmbSupp;
    private javax.swing.JTextField harga_satuan;
    private javax.swing.JTextField id_produk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nama_produk;
    private javax.swing.JTextField stock_produk;
    private javax.swing.JComboBox tahun;
    private javax.swing.JComboBox tanggal;
    private javax.swing.JLabel txtNamaB;
    private javax.swing.JLabel txtstock;
    private javax.swing.JLabel txtstock1;
    private javax.swing.JLabel txtstock2;
    private javax.swing.JLabel txtstock3;
    // End of variables declaration//GEN-END:variables
}
